
version: '3.8'

services:
  frontend:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL:-https://makeurlshort.onrender.com/api}
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - urlshortener

  backend:
    build: ../BACKEND
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - APP_URL=https://makeurlshort.onrender.com/
      - MONGO_URI=mongodb://mongodb:27017/urlshortener
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ALLOWED_ORIGINS=https://make-url-short.vercel.app
      - NODE_ENV=production
    depends_on:
      - mongodb
      - redis
    networks:
      - urlshortener

  mongodb:
    image: mongo:7-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - urlshortener

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - urlshortener

volumes:
  mongodb_data:
  redis_data:

networks:
  urlshortener:
    driver: bridge
